### ISSUE TITLE
Ansible play fails after new version of CitC

### ISSUE THREAD

**Issue by joeiznogood** [ACRC/cluster-in-the-cloud#5] opened 2019-04-15 06:24 UTC
Hi,

I just updated to the newest version of CitC and tried to start a cluster. When the ansible notebook is played, I get the following error:

> Starting Ansible Pull at 2019-04-15 06:12:47
> /usr/bin/ansible-pull --url=https://github.com/ACRC/slurm-ansible-playbook.git --checkout=master --inventory=/root/hosts management.yml
>  [WARNING]: Could not match supplied host pattern, ignoring: mgmt
>  [WARNING]: Your git version is too old to fully support the depth argument.
> Falling back to full checkouts.
> mgmt.subnetad1.clustervcn.oraclevcn.com | CHANGED => {
>     "after": "ece81babcd538714aa1a61a57c7eee75a51a79c6",
>     "before": null,
>     "changed": true
> }
>  [WARNING]: Could not match supplied host pattern, ignoring: mgmt
> 
> PLAY [finisher script] *********************************************************
> ...
> TASK [slurm : install Slurm] ***************************************************
> Monday 15 April 2019  06:14:55 +0000 (0:00:00.221)       0:02:04.207 **********
> failed: [mgmt.subnetad1.clustervcn.oraclevcn.com] (item=slurmctld) => changed=false
>   item: slurmctld
>   msg: No package matching 'slurm-slurmctld-17.11*' found available, installed or updated
>   rc: 126
>   results:
>   - No package matching 'slurm-slurmctld-17.11*' found available, installed or updated
> failed: [mgmt.subnetad1.clustervcn.oraclevcn.com] (item=slurmdbd) => changed=false
>   item: slurmdbd
>   msg: No package matching 'slurm-slurmdbd-17.11*' found available, installed or updated
>   rc: 126
>   results:
>   - No package matching 'slurm-slurmdbd-17.11*' found available, installed or updated
>  ....
> PLAY RECAP *********************************************************************
> mgmt.subnetad1.clustervcn.oraclevcn.com : ok=37   changed=35   unreachable=0    failed=1   

Sincerely,
Joe

**Comment by milliams** [comment] 2019-04-17 10:34
Duplicate of ACRC/slurm-ansible-playbook#25

**Closed as completed by milliams** 2019-04-17 10:34 UTC
Labels: duplicate
